// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDktgD7IvG8TxYFT8vGPMLLQaLRYmqj3E8',
    appId: '1:983799095293:web:18a8bee16ed036ab0f0394',
    messagingSenderId: '983799095293',
    projectId: 'flutter-chat-app-23b1d',
    authDomain: 'flutter-chat-app-23b1d.firebaseapp.com',
    storageBucket: 'flutter-chat-app-23b1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9W4Ro_e6In7G-vEsYiEKrWcnsMjGA4Hc',
    appId: '1:983799095293:android:e243b1d10d8dbdc30f0394',
    messagingSenderId: '983799095293',
    projectId: 'flutter-chat-app-23b1d',
    storageBucket: 'flutter-chat-app-23b1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK0vFaK16B85xbjziriGCRqCJkL153XVo',
    appId: '1:983799095293:ios:4b85fa0c463e97230f0394',
    messagingSenderId: '983799095293',
    projectId: 'flutter-chat-app-23b1d',
    storageBucket: 'flutter-chat-app-23b1d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK0vFaK16B85xbjziriGCRqCJkL153XVo',
    appId: '1:983799095293:ios:4b85fa0c463e97230f0394',
    messagingSenderId: '983799095293',
    projectId: 'flutter-chat-app-23b1d',
    storageBucket: 'flutter-chat-app-23b1d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDktgD7IvG8TxYFT8vGPMLLQaLRYmqj3E8',
    appId: '1:983799095293:web:2db1c3b03e1d5d3c0f0394',
    messagingSenderId: '983799095293',
    projectId: 'flutter-chat-app-23b1d',
    authDomain: 'flutter-chat-app-23b1d.firebaseapp.com',
    storageBucket: 'flutter-chat-app-23b1d.firebasestorage.app',
  );
}
